language: go
before_install:
  - sudo apt-get update -qq > apt-get.out || (cat apt-get.out && exit 1)
  - sudo apt-get install bzr mercurial git cmake -qq >> apt-get.out || (cat apt-get.out && exit 1)
install:
  - mkdir -p $GOPATH/src/github.com/globocom/tsuru-healer
  - mv * $GOPATH/src/github.com/globocom/tsuru-healer
  - pushd $GOPATH/src/github.com/globocom/tsuru-healer
  - make get-test
  - popd
before_script:
  - pushd $GOPATH/src/github.com/globocom/tsuru-healer
  - ./check-fmt.sh
  - make get-prod
  - popd
script:
  - pushd $GOPATH/src/github.com/globocom/tsuru-healer
  - make test
  - popd
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
  email:
    recipients:
      - tsuru@corp.globo.com
    on_success: change
    on_failure: always
